name: ğŸ‹ Release package

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout code
        uses: actions/checkout@v4

      - name: ğŸŒ± Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.nvmrc
          cache: 'npm'

      - name: ğŸ’» Install dependencies
        run: npm ci --legacy-peer-deps

      - name: ğŸ“ƒ Run lint
        run: npm run lint

      - name: ğŸ†’ Run type check
        run: npm run type:check

      - name: ğŸ‘·â€â™‚ï¸ Build project
        run: npm run build

      - name: ğŸ§ª Run tests
        run: npm test

      - name: ğŸ® Dry run semantic release
        run: npx semantic-release --dry-run --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish:
    runs-on: ubuntu-latest
    needs: tests

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: ğŸ” Checkout code
        uses: actions/checkout@v4

      - name: ğŸŒ± Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.nvmrc
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: ğŸ’» Install dependencies
        run: npm ci --ignore-scripts --only=dev

      - name: ğŸ‘·â€â™‚ï¸ Build package
        run: npm run build

      - name: ğŸ« Publish package
        run: npm run semantic-release --branches ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
